name: Packaging 📦

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      version_name:
        required: false
        type: string

jobs:
  package:
    name: Run production build 🏗️
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.commit }}
          submodules: true

      - name: Setup node environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: npm
          check-latest: true

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Build native shell
        env:
          VERSION_NAME: ${{ inputs.version_name }}
        run: npm run build:nativeshell

      - name: Build web
        run: npm run build:web

      - name: Package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package
          path: dist/package
